### PR TITLE
Fix Github tests

### LINKED ISSUE #1425: [Internal] Test failures on 4.2.0-dev
Some recent changes have resulted in this failure:

```
> Task :auth:testDebugUnitTest
Calling mockable JAR artifact transform to create file: /usr/local/google/home/samstern/.gradle/caches/transforms-1/files-1.1/android.jar/f63758f093c923ec5f3cd772b2994b46/android.jar with input /usr/local/google/home/samstern/android-sdk-linux/platforms/android-27/android.jar

com.firebase.ui.auth.viewmodel.SocialProviderResponseHandlerTest > testSignInIdp_anonymousUserUpgradeEnabledAndExistingPasswordUserWithDifferentIdp_expectMergeFailure FAILED
    java.lang.RuntimeException at SocialProviderResponseHandlerTest.java:319

com.firebase.ui.auth.viewmodel.SocialProviderResponseHandlerTest > testSignInIdp_anonymousUserUpgradeEnabledAndExistingIdpUserWithDifferentIdp_expectMergeFailure FAILED
    java.lang.RuntimeException at SocialProviderResponseHandlerTest.java:319

com.firebase.ui.auth.viewmodel.SocialProviderResponseHandlerTest > testSignInIdp_anonymousUserUpgradeEnabledAndNewUser_expectSuccess FAILED
    java.lang.RuntimeException at SocialProviderResponseHandlerTest.java:319

com.firebase.ui.auth.viewmodel.SocialProviderResponseHandlerTest > testSignInIdp_anonymousUserUpgradeEnabledAndExistingUserWithSameIdp_expectMergeFailure FAILED
    java.lang.RuntimeException at SocialProviderResponseHandlerTest.java:319

91 tests completed, 4 failed
```

Assigning this to myself to fix, just filing this for tracking.

### PR DESCRIPTION
**Pull request by samtstern**
This fixes #1425 

We can't add a dependency from `auth` to `auth-github` because that would be circular.

Maybe we need an `auth-common` module in the long term?  That would be a bit unfortunate, but could fix the issue.

### CODE REVIEW

File: auth/src/main/java/com/firebase/ui/auth/AuthUI.java [hunk 1]
```diff
@@ -120,13 +120,15 @@
...
+     *
+     * TODO: the Github provider is not included because these tests do not
+     *       depend on the required auth-github module.
      */
     public static final Set<String> SUPPORTED_PROVIDERS =
             Collections.unmodifiableSet(new HashSet<>(Arrays.asList(
                     GoogleAuthProvider.PROVIDER_ID,
                     FacebookAuthProvider.PROVIDER_ID,
                     TwitterAuthProvider.PROVIDER_ID,
-                    GithubAuthProvider.PROVIDER_ID,
```
Comment (SUPERCILEX) [inline auth/src/main/java/com/firebase/ui/auth/AuthUI.java]: Whoa, that's a public API, not part of `TestConstants`. 😛 I wasn't merged up with master before so I didn't see the changes. Here's how I fixed it:
https://github.com/firebase/FirebaseUI-Android/blob/98353a7164e4a55ca74538ea720069946193de28/auth/src/test/java/com/firebase/ui/auth/viewmodel/SocialProviderResponseHandlerTest.java#L74-L76

If we did that here:
https://github.com/firebase/FirebaseUI-Android/blob/98353a7164e4a55ca74538ea720069946193de28/auth/src/test/java/com/firebase/ui/auth/viewmodel/SocialProviderResponseHandlerTest.java#L319-L320
it should work.

Comment (SUPERCILEX) [reply auth/src/main/java/com/firebase/ui/auth/AuthUI.java]: But yeah, I couldn't find a way to include GitHub in the tests. 😢
